# cloudbuild.yaml
# gcloud builds submit --config cloudbuild.yaml .
steps:
  # build & push the container image
  - name: "gcr.io/kaniko-project/executor:latest"
    args: ["--cache=true", "--cache-ttl=48h", "--destination=gcr.io/$PROJECT_ID/pastebin:latest"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: ['beta', 'run', 'deploy', 'pastebin', '--image', 'gcr.io/$PROJECT_ID/pastebin:latest', '--region', 'us-east4', '--allow-unauthenticated', '--platform', 'managed']